remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Project 7
description: In this project we created an initial version of our CIT Minor portfolio using GitHub Pages. Created 16 repos for all projects and labs, with each having their own GitHub sites
